"""
example/entity_camera_relationship/main.py
==========================================
This example is generated by Claude Code AI

WHAT THIS EXAMPLE TEACHES
--------------------------
In a scrollable game world, there are three coordinate spaces you need to
understand. Confusing them is the #1 source of bugs when combining entities
with a camera.

  1. WORLD SPACE
     The full game map, as large as it needs to be.
     An entity's "true" position lives here — it never changes just because
     the player scrolls the screen.
     e.g., player is at world (2100, 800) on a 4113×1598 map.

  2. CAMERA SPACE  (also called "view space")
     A rectangle cut out of world space that represents what's visible.
     The camera's (x, y) is the world coordinate of its TOP-LEFT corner.
     e.g., camera top-left is at world (1632, 565) — meaning the screen
     shows a 960×540 slice of the map starting from that point.

  3. SCREEN SPACE
     Pixel coordinates on the actual window (always 0..width, 0..height).
     To convert from world → screen, subtract the camera position:

         screen_x = world_x - camera_x
         screen_y = world_y - camera_y

     e.g., player at world (2100, 800) with camera at (1632, 565):
         screen_x = 2100 - 1632 = 468
         screen_y = 800  - 565  = 235
     So the player sprite is drawn at pixel (468, 235) on the window.

CAMERA FOLLOW STRATEGY (used here: "locked center")
----------------------------------------------------
The simplest approach: keep the entity centered on screen at all times.

    target_cam_x = entity.world_x - SCREEN_W / 2
    target_cam_y = entity.world_y - SCREEN_H / 2

But this would show black space when the entity is near a map edge.
So we CLAMP the camera to stay inside the map bounds:

    cam_x = clamp(target_cam_x, 0, map_width  - SCREEN_W)
    cam_y = clamp(target_cam_y, 0, map_height - SCREEN_H)

    where clamp(value, lo, hi) = max(lo, min(value, hi))

Notice the entity appears to "slide off-center" when near an edge —
that is the correct behavior: the camera hits its limit but the entity
keeps moving.

HOW TO RUN
----------
From the project root (M151_Engine/):
    python example/entity_camera_relationship/main.py

Controls:
    WASD  — move the entity
    ESC   — quit

Watch the debug HUD in the top-left corner: world and camera coordinates
change constantly while screen_x / screen_y stay near the window center.
That relationship IS the entity–camera system.
"""

import sys
import pygame
from pathlib import Path


# ── Resolve asset paths regardless of where you run the script from ─────────
#
# This file lives at: M151_Engine/example/entity_camera_relationship/main.py
#   Path(__file__).resolve()      → absolute path to this file
#   .parent                       → entity_camera_relationship/
#   .parent.parent                → example/
#   .parent.parent.parent         → M151_Engine/  ← project root
#
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
CHAR_SHEET   = PROJECT_ROOT / "assets" / "images" / "characters" / "characters.png"
MAP_IMAGE    = PROJECT_ROOT / "assets" / "images" / "background" / "land" / "test-land.png"


# ── Display settings ─────────────────────────────────────────────────────────
SCREEN_W = 960
SCREEN_H = 540


# ── Spritesheet constants (see main_character_actions.py for full explanation)
#
# characters.png is a grid of 32×32 sprite cells separated by 1-pixel lines.
# Column x-positions start at x=10, then repeat every 33 pixels (32 + 1 sep).
# Row y-positions: row 0 starts at y=25, row 1 starts at y=58.
#
SPRITE_W  = 32
SPRITE_H  = 32
_COL_X    = [10 + col * 33 for col in range(4)]   # [10, 43, 76, 109]
_ROW_Y    = [25, 58]
_COLORKEY = (32, 200, 248)   # cyan background → transparent

# Maps each direction string to its (sheet_row, sheet_col) in characters.png
_DIR_COORDS = {
    "up_left":    (0, 0),
    "up":         (0, 1),
    "up_right":   (0, 2),
    "right":      (0, 3),
    "left":       (1, 0),
    "down_left":  (1, 1),
    "down":       (1, 2),
    "down_right": (1, 3),
}


# ════════════════════════════════════════════════════════════════════════════
# HELPER: spritesheet loader
# ════════════════════════════════════════════════════════════════════════════

def load_frames() -> dict[str, pygame.Surface]:
    """
    Cut characters.png into one 32×32 Surface per direction.
    Returns a dict: {"up": Surface, "down_right": Surface, ...}
    """
    sheet  = pygame.image.load(str(CHAR_SHEET)).convert_alpha()
    frames = {}
    for direction, (row, col) in _DIR_COORDS.items():
        # Create a blank surface the size of one sprite cell
        frame = pygame.Surface((SPRITE_W, SPRITE_H))
        # Copy the correct cell out of the big spritesheet
        # blit(source, dest_pos, source_rect)
        frame.blit(sheet, (0, 0), pygame.Rect(_COL_X[col], _ROW_Y[row], SPRITE_W, SPRITE_H))
        # Mark the cyan color as transparent (colorkey = "treat this color as alpha=0")
        frame.set_colorkey(_COLORKEY)
        frames[direction] = frame
    return frames


# ════════════════════════════════════════════════════════════════════════════
# HELPER: keyboard input
# ════════════════════════════════════════════════════════════════════════════

def read_keys() -> tuple[float, float, str | None]:
    """
    Poll WASD keys. Returns (dx, dy, direction_string_or_None).

    dx and dy are unit-length components of a movement direction.
    They get multiplied by speed and dt inside Entity.update().

    WHY NORMALIZE DIAGONALS?
    -------------------------
    Pure cardinal input (e.g., W only):
        dx=0, dy=-1  → magnitude = √(0²+1²) = 1.0  ✓

    Naive diagonal input (W+D):
        dx=1, dy=-1  → magnitude = √(1²+1²) = 1.414  ✗

    The entity would move 41% faster diagonally. To fix this, multiply
    diagonal components by 1/√2 ≈ 0.707, which scales them so the
    combined vector has magnitude 1.0 again:

        dx = 0.707, dy = -0.707  → magnitude = √(0.707²+0.707²) = 1.0  ✓
    """
    DIAG = 0.707   # 1 / √2

    keys = pygame.key.get_pressed()
    w = keys[pygame.K_w]
    s = keys[pygame.K_s]
    a = keys[pygame.K_a]
    d = keys[pygame.K_d]

    # Python's match statement on a tuple of booleans is a clean way to
    # handle 8-directional logic without a chain of if/elif.
    # Opposing keys (W+S or A+D) fall through to the default: no movement.
    match (w, s, a, d):
        case (True,  False, True,  False): return (-DIAG, -DIAG, "up_left")
        case (True,  False, False, True):  return ( DIAG, -DIAG, "up_right")
        case (False, True,  True,  False): return (-DIAG,  DIAG, "down_left")
        case (False, True,  False, True):  return ( DIAG,  DIAG, "down_right")
        case (True,  False, False, False): return ( 0.0,  -1.0,  "up")
        case (False, True,  False, False): return ( 0.0,   1.0,  "down")
        case (False, False, True,  False): return (-1.0,   0.0,  "left")
        case (False, False, False, True):  return ( 1.0,   0.0,  "right")
        case _:                            return ( 0.0,   0.0,  None)


# ════════════════════════════════════════════════════════════════════════════
# ENTITY
# ════════════════════════════════════════════════════════════════════════════

class Entity:
    """
    An entity exists in WORLD SPACE.

    world_x and world_y are its position on the full game map.
    They have nothing to do with where the sprite appears on screen —
    that conversion is done externally by the Camera.

    Keeping world position and screen position strictly separate is what
    makes the camera system work. The entity never needs to know about
    the camera, and the camera never needs to know about gameplay logic.
    """

    SPEED = 220   # pixels per second in world space

    def __init__(self, world_x: float, world_y: float, frames: dict):
        self.world_x   = float(world_x)
        self.world_y   = float(world_y)
        self.direction = "down"   # facing direction, used to pick the sprite frame
        self.frames    = frames

        # Scale up for visibility: 32×32 px is tiny on a modern screen
        self.scale  = 4
        self.draw_w = SPRITE_W * self.scale   # 128 px
        self.draw_h = SPRITE_H * self.scale   # 128 px

    def update(self, dt: float, map_w: int, map_h: int) -> None:
        """
        Read input, move in world space, clamp to map boundaries.

        DELTA-TIME (dt):
            dt = seconds elapsed since the previous frame.
            At 60 fps → dt ≈ 0.0167 s  →  220 * 0.0167 ≈  3.7 px per frame
            At 30 fps → dt ≈ 0.0333 s  →  220 * 0.0333 ≈  7.3 px per frame

            Either way, over one full second the entity travels 220 pixels.
            Without dt the entity would move faster on faster hardware.

        MAP BOUNDARY CLAMP:
            Ensure the sprite stays fully inside the map.
            The upper limit is (map_dimension - sprite_dimension) rather than
            map_dimension alone, because (world_x, world_y) is the sprite's
            TOP-LEFT corner — if we clamped to map_w the right edge of the
            sprite would extend 128 px past the map boundary.
        """
        dx, dy, new_dir = read_keys()

        if new_dir is not None:
            self.direction = new_dir

        self.world_x += dx * self.SPEED * dt
        self.world_y += dy * self.SPEED * dt

        # Clamp: keep the sprite fully inside the map
        self.world_x = max(0.0, min(self.world_x, map_w - self.draw_w))
        self.world_y = max(0.0, min(self.world_y, map_h - self.draw_h))

    def draw(self, screen: pygame.Surface, screen_x: float, screen_y: float) -> None:
        """
        Draw the sprite at (screen_x, screen_y) — NOT at world_x / world_y.

        The caller computes (screen_x, screen_y) via Camera.world_to_screen()
        before calling this method. The entity itself has no knowledge of
        the camera — it just accepts the screen position and draws there.
        """
        sprite = self.frames[self.direction]
        scaled = pygame.transform.scale(sprite, (self.draw_w, self.draw_h))
        screen.blit(scaled, (int(screen_x), int(screen_y)))


# ════════════════════════════════════════════════════════════════════════════
# CAMERA
# ════════════════════════════════════════════════════════════════════════════

class Camera:
    """
    The camera defines a rectangular window into the world.

    self.x, self.y  →  world coordinates of the camera's TOP-LEFT corner.
                       "How far into the world have we scrolled?"

    Visual diagram:

        World map  (4113 × 1598 px)
        ┌──────────────────────────────────────────────────┐
        │                                                  │
        │   (cam_x, cam_y)                                 │
        │   ┌────────────────────┐ ← Camera viewport       │
        │   │   (screen 960×540) │                         │
        │   │                   │                         │
        │   │     [entity]       │                         │
        │   │                   │                         │
        │   └────────────────────┘                         │
        │                                                  │
        └──────────────────────────────────────────────────┘

    Only what's inside the camera rect is visible on screen.
    Everything outside is simply not drawn.
    """

    def __init__(self, screen_w: int, screen_h: int, player:Entity):
        self.screen_w = screen_w
        self.screen_h = screen_h
        self.x = player.world_x-screen_w/2.5   # world x of the camera's left edge
        self.y = player.world_y-screen_h/2.5 * 2
           # world y of the camera's top edge    

    def follow(self, entity: Entity, map_w: int, map_h: int) -> None:
        """
        Update the camera position to keep the entity centered on screen,
        clamped so we never show outside the map.

        ── STEP 1: aim for the entity's center ──────────────────────────────

        We want the VISUAL CENTER of the entity sprite to sit at the center
        of the screen. The sprite's visual center in world space is:

            center_x = entity.world_x + entity.draw_w / 2
            center_y = entity.world_y + entity.draw_h / 2

        For the camera's top-left to place that center in the middle of
        the screen, the camera must be at:

            target_x = center_x - screen_w / 2
            target_y = center_y - screen_h / 2

        You can verify this: if camera is at target_x,
            screen position of center = center_x - target_x
                                      = center_x - (center_x - screen_w/2)
                                      = screen_w / 2  ✓  (exactly the middle)

        ── STEP 2: clamp to map boundaries ──────────────────────────────────

        The camera's top-left must stay inside:

            x ∈ [0,  map_w - screen_w]
            y ∈ [0,  map_h - screen_h]

        If x < 0:             camera shows left of the map  → black strip.
        If x > map_w-screen_w: camera shows right of the map → black strip.

        When the entity is near an edge, the camera "stops" at the clamp
        limit while the entity continues moving. The entity visually slides
        toward the edge of the screen — this is the expected, correct behavior.
        """
        # Entity's visual center in world space
        center_x = entity.world_x + entity.draw_w / 2
        center_y = entity.world_y + entity.draw_h / 2

        # Ideal camera top-left to center on that point

        #original always center
        #target_x = center_x - self.screen_w / 2
        target_x = self.x
        target_y = self.y

        if(center_x - target_x) <= self.screen_w / 3:
            target_x = center_x - self.screen_w / 3
        elif (center_x - target_x) >= self.screen_w / 3 * 2:
            target_x = center_x - self.screen_w / 3 * 2


        if(center_y - target_y) <= self.screen_h / 2:
            target_y = center_y - self.screen_h / 2
        elif(center_y - target_y) >= self.screen_h / 5 * 4:
            target_y = center_y - self.screen_h / 5 * 4
        # Clamp: don't scroll past map edges
        #self.x = max(0.0, min(target_x, float(map_w - self.screen_w)))
        self.x = max(0.0, min(target_x, float(map_w - self.screen_w)))
        self.y = max(0.0, min(target_y, float(map_h - self.screen_h)))

    def world_to_screen(self, world_x: float, world_y: float) -> tuple[float, float]:
        """
        Convert any world-space coordinate to a screen-space coordinate.

        FORMULA:
            screen_x = world_x - cam_x
            screen_y = world_y - cam_y

        INTUITION:
            cam_x represents how far the camera has scrolled to the right.
            Subtracting it from a world x-coordinate "un-scrolls" it —
            it gives you where that world point appears relative to the
            left edge of the screen.

            Worked example:
                Entity is at world (2100, 800).
                Camera top-left is at world (1632, 565).
                screen_x = 2100 - 1632 = 468
                screen_y = 800  - 565  = 235
                → sprite is drawn at pixel (468, 235) on the window.

        NOTE: This formula works for ANY world object — enemies, items,
        particles, UI elements anchored to world positions, etc.
        Always subtract the camera before drawing anything in world space.
        """
        return world_x - self.x, world_y - self.y

    def draw_map(self, screen: pygame.Surface, map_surface: pygame.Surface) -> None:
        """
        Draw only the visible slice of the map onto the screen.

        EFFICIENT APPROACH — use pygame's area= parameter:
            screen.blit(map_surface, dest=(0,0), area=(cam_x, cam_y, W, H))

            This tells pygame: "starting at pixel (cam_x, cam_y) in the
            source image, copy a W×H rectangle and place it at (0,0) on
            the destination surface."

            Only 960×540 pixels are copied per frame, regardless of how
            large the map is. Blitting the full 4113×1598 map every frame
            would be far slower and unnecessary.

        ALTERNATIVE (simpler to understand, but slower):
            screen.blit(map_surface, (-cam_x, -cam_y))

            This draws the entire map at an offset, which achieves the
            same visual result but sends millions of off-screen pixels
            through the renderer unnecessarily.
        """
        screen.blit(
            map_surface,
            (0, 0),
            area=(int(self.x), int(self.y), self.screen_w, self.screen_h),
        )


# ════════════════════════════════════════════════════════════════════════════
# DEBUG OVERLAY
# ════════════════════════════════════════════════════════════════════════════

def draw_debug(
    screen: pygame.Surface,
    font: pygame.font.Font,
    player: Entity,
    camera: Camera,
) -> None:
    """
    HUD showing all three coordinate spaces simultaneously.

    While you move, notice:
      - world_x / world_y change continuously with input.
      - camera_x / camera_y track the player (with clamping near edges).
      - screen_x / screen_y stay near (480, 270) — the screen center —
        except when the camera is clamped at a map boundary.

    That last point is the key insight: screen position is DERIVED from
    world minus camera. You never set it directly.
    """
    sx, sy = camera.world_to_screen(player.world_x, player.world_y)

    lines = [
        f"  world  : ({player.world_x:7.1f}, {player.world_y:7.1f})",
        f"  camera : ({camera.x:7.1f}, {camera.y:7.1f})",
        f"  screen : ({sx:7.1f}, {sy:7.1f})  = world - camera",
    ]

    panel_w = 340
    panel_h = len(lines) * 18 + 12
    panel   = pygame.Surface((panel_w, panel_h), pygame.SRCALPHA)
    panel.fill((0, 0, 0, 160))   # semi-transparent black
    screen.blit(panel, (6, 6))

    for i, line in enumerate(lines):
        text = font.render(line, True, (180, 255, 160))
        screen.blit(text, (8, 10 + i * 18))


# ════════════════════════════════════════════════════════════════════════════
# ENTRY POINT
# ════════════════════════════════════════════════════════════════════════════

def main() -> None:
    pygame.init()
    screen = pygame.display.set_mode((SCREEN_W, SCREEN_H))
    pygame.display.set_caption("Entity–Camera Relationship — M151 Engine Example")
    clock = pygame.time.Clock()
    font  = pygame.font.SysFont("monospace", 14)

    # Load assets
    map_surface      = pygame.image.load(str(MAP_IMAGE)).convert()
    map_w, map_h     = map_surface.get_size()
    frames           = load_frames()

    # Spawn the player near the center of the world map
    player = Entity(world_x=map_w / 2, world_y=map_h / 2, frames=frames)

    camera = Camera(SCREEN_W, SCREEN_H, player)

    running = True
    while running:
        # ── Time ────────────────────────────────────────────────────────────
        # clock.tick(60) sleeps until 1/60th of a second has passed since
        # the last call, then returns the actual milliseconds elapsed.
        # Dividing by 1000 gives dt in seconds, which scales movement correctly.
        dt = clock.tick(60) / 1000.0

        # ── Events ──────────────────────────────────────────────────────────
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                running = False

        # ── Update ──────────────────────────────────────────────────────────

        # 1. Move the entity in world space.
        player.update(dt, map_w, map_h)

        # 2. Update the camera AFTER the entity moves.
        #    This ensures the camera tracks the entity's NEW position.
        #    (If you swapped these, the camera would always be one frame behind.)
        camera.follow(player, map_w, map_h)

        # ── Draw ────────────────────────────────────────────────────────────
        # Drawing order matters: map first, then entities on top.

        # 3. Draw the visible slice of the world map.
        camera.draw_map(screen, map_surface)

        # 4. Convert the entity's world position to screen position, then draw.
        #    This single line IS the entity–camera relationship in practice:
        #        subtract camera → get screen coordinates → draw there.
        screen_x, screen_y = camera.world_to_screen(player.world_x, player.world_y)
        player.draw(screen, screen_x, screen_y)

        # 5. Debug overlay (drawn last so it appears on top of everything)
        draw_debug(screen, font, player, camera)

        pygame.display.flip()

    pygame.quit()
    sys.exit()


if __name__ == "__main__":
    main()
